/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.ebi.metabolomes.parser.brenda;

import java.util.Map;
import java.util.HashMap;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author pmoreno
 */
public class ProteinSmallMoleculeDeciderTest {

    private final Map<String, Boolean> candidates2expectedOutcome = new HashMap<String, Boolean>();

    public ProteinSmallMoleculeDeciderTest() {
    }

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() {
        candidates2expectedOutcome.put("6-(2,6-Bis[N-acetyl-beta-D-glucosaminyl]-alpha-D-mannosyl)-beta-D- mannosyl-R", false);
        candidates2expectedOutcome.put("Dermatan", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-glycopeptide", false);
        candidates2expectedOutcome.put("Phosphatidylcholine", false);
        candidates2expectedOutcome.put("m7G(5')pppm6Am (mRNA containing an N6,2'-O-dimethyladenosine cap)", false);
        candidates2expectedOutcome.put("alpha-L-Fucoside", false);
        candidates2expectedOutcome.put("1-Organyl-2-lyso-sn-glycero-3-phosphocholine", false);
        candidates2expectedOutcome.put("Acyl phosphate", false);
        candidates2expectedOutcome.put("Phosphatidylinositol-3,4,5-trisphosphate", false);
        candidates2expectedOutcome.put("tRNA(Asn)", false);
        candidates2expectedOutcome.put("Cytochrome c", true);
        candidates2expectedOutcome.put("3-Oxooctanoyl-[acp]", true);
        candidates2expectedOutcome.put("beta-D-Glucuronosyl-(1->4)-N-acetyl-alpha-D-glucosaminylproteoglycan", false);
        candidates2expectedOutcome.put("ROH", false);
        candidates2expectedOutcome.put("m7G(5')pppR-RNA", false);
        candidates2expectedOutcome.put("Amine", false);
        candidates2expectedOutcome.put("Peptidyl-L-lysyl-peptide", false);
        candidates2expectedOutcome.put("tRNA queuine", false);
        candidates2expectedOutcome.put("Protein", true);
        candidates2expectedOutcome.put("N-Acylsphingosine", false);
        candidates2expectedOutcome.put("trans-3-Enoyl-CoA", false);
        candidates2expectedOutcome.put("3-(Acyloxy)acyl group of bacterial toxin", false);
        candidates2expectedOutcome.put("1,4-beta-D-Galactosyl-N-acetyl-D-glucosaminyl-R", false);
        candidates2expectedOutcome.put("Mononucleotide", false);
        candidates2expectedOutcome.put("N-Substituted aminoacyl-tRNA", false);
        candidates2expectedOutcome.put("Protein N5-alkylglutamine", true);
        candidates2expectedOutcome.put("tRNA(Met)", false);
        candidates2expectedOutcome.put("N-Acyl-D-glucosamine", false);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,4-N-acetyl-beta-D-glucosaminyl-1,3-beta-D- galactosyl-1,4-beta-D-glucosylceramide", false);
        candidates2expectedOutcome.put("Protein glutamine", true);
        candidates2expectedOutcome.put("beta-D-Mannoside", false);
        candidates2expectedOutcome.put("RNA", false);
        candidates2expectedOutcome.put("Apo-[carboxylase]", true); // Should be true
        candidates2expectedOutcome.put("Protein tyrosine", true);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-galactosaminyl-1,4-beta-D-glucuronyl-N-acetyl-1,3- beta-D-galactosaminylproteoglycan", false);
        candidates2expectedOutcome.put("3-beta-D-Glucuronosyl-3-beta-D-galactosyl-4-beta-D-galactosyl-O- beta-D-xylosylprotein", true);
        candidates2expectedOutcome.put("Starch", false);
        candidates2expectedOutcome.put("O-Alkylglycerone phosphate", false);
        candidates2expectedOutcome.put("tRNA(Asp)", false);
        candidates2expectedOutcome.put("2,3-Dehydroacyl-CoA", false);
        candidates2expectedOutcome.put("Alkyl sulfate", false);
        candidates2expectedOutcome.put("Peptidylglycine", false);
        candidates2expectedOutcome.put("Glycoprotein with the oligosaccharide chain attached by N-glycosyl linkage to protein L-asparagine", true);
        candidates2expectedOutcome.put("Ketone", false);
        candidates2expectedOutcome.put("Alcohol", false);
        candidates2expectedOutcome.put("N-Acetyl-alpha-D-galactosaminyl-(1,3)-[alpha-L-fucosyl-(1,2)]-D- galactoside", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,3-beta-D-galactosyl-1,4-N-acetyl-D- glucosaminyl-R", false);
        candidates2expectedOutcome.put("Protein N6-(octanoyl)lysine", true);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,3-(N-acetyl-beta-D-glucosaminyl-1,6)-N-acetyl-D- galactosaminyl-R", false);
        candidates2expectedOutcome.put("alpha-N-Acetyl-D-glucosaminyl-(1->4)-beta-D-glucuronosyl-(1->3)- beta-D-galactosyl-(1->3)-beta-D-galactosyl-(1->4)-beta-D- xylosylproteoglycan", false);
        candidates2expectedOutcome.put("m7G(5')pppAm", false);
        candidates2expectedOutcome.put("[Isocitrate dehydrogenase (NADP+)]", true);
        candidates2expectedOutcome.put("Apocytochrome c", true);
        candidates2expectedOutcome.put("2'-Deoxyribonucleoside diphosphate", false);
        candidates2expectedOutcome.put("Sphingomyelin", false);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactose-1,3-(alpha-N- acetylneuraminyl-2,6)-N-acetyl-D-galactosaminyl-R", false);
        candidates2expectedOutcome.put("Acyl-CoA", false);
        candidates2expectedOutcome.put("Polyphosphate", false);
        candidates2expectedOutcome.put("Enzyme N6-(lipoyl)lysine", true);
        candidates2expectedOutcome.put("Phosphatidylglycerophosphate", false);
        candidates2expectedOutcome.put("tRNA adenine", false);
        candidates2expectedOutcome.put("N-Acetyl-alpha-D-glucosaminyl-(1->4)-beta-D-glucuronosyl-(1->4)-N- acetyl-alpha-D-glucosaminylproteoglycan", false);
        candidates2expectedOutcome.put("Orthophosphoric monoester", false);
        candidates2expectedOutcome.put("Keratan sulfate", false);
        candidates2expectedOutcome.put("1-Alkyl-sn-glycero-3-phosphate", false);
        candidates2expectedOutcome.put("3-Oxotetradecanoyl-[acp]", true);
        candidates2expectedOutcome.put("Procollagen L-proline", true);
        candidates2expectedOutcome.put("Phosphatidylserine", false);
        candidates2expectedOutcome.put("Glycylpeptide", false);
        candidates2expectedOutcome.put("Histone L-arginine", true);
        candidates2expectedOutcome.put("Secondary alcohol", false);
        candidates2expectedOutcome.put("1,2-Diacyl-sn-glycerol", false);
        candidates2expectedOutcome.put("trans-Dec-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("Protein N6-[(R)-4-amino-2-hydroxybutyl]-L-lysine", true);
        candidates2expectedOutcome.put("beta-Adrenergic receptor", true);
        candidates2expectedOutcome.put("Fatty acid", false);
        candidates2expectedOutcome.put("5'-Phospho-DNA", false);
        candidates2expectedOutcome.put("Oleoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("Phosphatidyl-N-methylethanolamine", false);
        candidates2expectedOutcome.put("L-Phenylalanyl-tRNA(Phe)", false);
        candidates2expectedOutcome.put("Peptide-L-methionine (S)-S-oxide", false);
        candidates2expectedOutcome.put("Sulfuric monoester", false);
        candidates2expectedOutcome.put("[Dihydrolipoyllysine-residue succinyltransferase] S-succinyldihydrolipoyllysine", true);
        candidates2expectedOutcome.put("CMP-N-acylneuraminate", false);
        candidates2expectedOutcome.put("Protein L-isoaspartate methyl ester", true);
        candidates2expectedOutcome.put("3-Oxoadipyl-CoA", false);
        candidates2expectedOutcome.put("Lysosomal-enzyme D-mannose", true);
        candidates2expectedOutcome.put("Peptidylamidoglycolate", false);
        candidates2expectedOutcome.put("Thiol-containing reductant", false);
        candidates2expectedOutcome.put("Trihexosylceramide", false);
        candidates2expectedOutcome.put("Phosphatidate", false);
        candidates2expectedOutcome.put("tRNA(Pro)", false);
        candidates2expectedOutcome.put("[Methylmalonyl-CoA:pyruvate carboxytransferase]", true);
        candidates2expectedOutcome.put("Protein S-methyl-L-cysteine", true);
        candidates2expectedOutcome.put("1-Phosphatidyl-1D-myo-inositol 3,4-bisphosphate", false);
        candidates2expectedOutcome.put("(5-L-Glutamyl)-L-amino acid", false);
        candidates2expectedOutcome.put("D-Glucuronyl-N-acetyl-1,3-beta-D-galactosaminylproteoglycan", false);
        candidates2expectedOutcome.put("(3R)-3-Hydroxyoctanoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("alpha-L-Fucosyl-1,2-beta-D-galactoside", false);
        candidates2expectedOutcome.put("D-Amino acid", false);
        candidates2expectedOutcome.put("trans-Dodec-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("Protein N6,N6-dimethyl-L-lysine", true);
        candidates2expectedOutcome.put("Halide", false);
        candidates2expectedOutcome.put("Phosphatidylethanolamine", false);
        candidates2expectedOutcome.put("(2R)-2-Methylacyl-CoA", false);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactosyl-R", false);
        candidates2expectedOutcome.put("Protein disulfide", true);
        candidates2expectedOutcome.put("tRNA(Ile)", false);
        candidates2expectedOutcome.put("beta-D-Glucuronosyl-(1->3)-N-acetyl-beta-D-galactosaminyl-(1->4)- beta-D-glucuronosylproteoglycan", false);
        candidates2expectedOutcome.put("6-(alpha-D-Glucosaminyl)-1-phosphatidyl-1D-myo-inositol", false);
        candidates2expectedOutcome.put("[Propionyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("N-(4-Aminobutylidene)-[eIF5A-precursor]-lysine", true);
        candidates2expectedOutcome.put("Lysosomal-enzyme N-acetyl-D-glucosaminyl-phospho-D-mannose", true);
        candidates2expectedOutcome.put("Amino acid", false);
        candidates2expectedOutcome.put("tRNA(His)", false);
        candidates2expectedOutcome.put("alpha-Amino acid", false);
        candidates2expectedOutcome.put("Glycyl-tRNA(Gly)", false);
        candidates2expectedOutcome.put("Polypeptide", false);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,4-beta-D-glucosylceramide", false);
        candidates2expectedOutcome.put("(3R)-3-Hydroxybutanoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("1,3-beta-D-Galactosyl-(alpha-1,4-L-fucosyl)-N-acetyl-D-glucosaminyl- R", false);
        candidates2expectedOutcome.put("DNA 5-methylcytosine", false);
        candidates2expectedOutcome.put("L-Seryl-tRNA(Sec)", false);
        candidates2expectedOutcome.put("[Enzyme]-S-sulfanylcysteine", true);
        candidates2expectedOutcome.put("5-Oxoprolyl-peptide", false);
        candidates2expectedOutcome.put("[eIF5A-precursor]-deoxyhypusine", true);
        candidates2expectedOutcome.put("tRNA(Arg)", false);
        candidates2expectedOutcome.put("beta-D-Mannosyl-R", false);
        candidates2expectedOutcome.put("[Heparan sulfate]-glucosamine 3-sulfate", false);
        candidates2expectedOutcome.put("N-Acetyl-2-arylethylamine", false);
        candidates2expectedOutcome.put("Protein serine", true);
        candidates2expectedOutcome.put("N-Acyl-D-mannosamine", false);
        candidates2expectedOutcome.put("1,4-beta-D-Galactosyl-(alpha-1,3-L-fucosyl)-N-acetyl-D-glucosaminyl- R", false);
        candidates2expectedOutcome.put("CDP-diacylglycerol", false);
        candidates2expectedOutcome.put("L-Leucyl-tRNA", false);
        candidates2expectedOutcome.put("Glycogenin", true);
        candidates2expectedOutcome.put("Dialkyl phosphate", false);
        candidates2expectedOutcome.put("Glycoprotein phospho-D-mannose", true);
        candidates2expectedOutcome.put("Acetyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("N-Formylmethionyl-tRNA", false);
        candidates2expectedOutcome.put("[Dihydrolipoyllysine-residue acetyltransferase] S-acetyldihydrolipoyllysine", true);
        candidates2expectedOutcome.put("Long-chain fatty acid", false);
        candidates2expectedOutcome.put("Glutaminyl-tRNA", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-galactosaminyl-(1->4)-beta-D- glucuronosylproteoglycan", false);
        candidates2expectedOutcome.put("tRNA containing N2-methylguanine", false);
        candidates2expectedOutcome.put("Hexadecanoyl-[acp]", true);
        candidates2expectedOutcome.put("3',5'-Cyclic nucleotide", false);
        candidates2expectedOutcome.put("L-Alanyl-tRNA", false);
        candidates2expectedOutcome.put("Procollagen 5-hydroxy-L-lysine", true);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactosyl-1,4-N-acetyl-D- glucosaminyl-glycoprotein", true);
        candidates2expectedOutcome.put("Dinucleotide", false);
        candidates2expectedOutcome.put("alpha-D-Glucosylglycogenin", true);
        candidates2expectedOutcome.put("L-Amino acid", false);
        candidates2expectedOutcome.put("L-Asparaginyl-tRNA(Asn)", false);
        candidates2expectedOutcome.put("Butyryl-[acp]", true);
        candidates2expectedOutcome.put("Protein C-terminal S-farnesyl-L-cysteine", true);
        candidates2expectedOutcome.put("Ribonucleoside diphosphate", false);
        candidates2expectedOutcome.put("tRNA(Ser)", false);
        candidates2expectedOutcome.put("Peptide-L-methionine", false);
        candidates2expectedOutcome.put("Apoprotein", true);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,6-(N-acetyl-beta-D-glucosaminyl-1,2)- (N-acetyl-beta-D-glucosaminyl-1,4)-alpha-D-mannosyl-R", false);
        candidates2expectedOutcome.put("Acylcholine", false);
        candidates2expectedOutcome.put("Thioredoxin disulfide", true);
        candidates2expectedOutcome.put("tRNA(Tyr)", false);
        candidates2expectedOutcome.put("G(5')pppR-RNA", false);
        candidates2expectedOutcome.put("trans-Oct-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("Peptidylproline (omega=0)", false);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactosyl-1,3-N-acetyl-D- galactosaminyl-R", false);
        candidates2expectedOutcome.put("trans-2,3-Dehydroacyl-CoA", false);
        candidates2expectedOutcome.put("Glycoprotein N-acetyl-D-glucosaminyl-phospho-D-mannose", true);
        candidates2expectedOutcome.put("3-Oxohexadecanoyl-[acp]", true);
        candidates2expectedOutcome.put("DNA adenine", false);
        candidates2expectedOutcome.put("Dodecanoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("Thiol", false);
        candidates2expectedOutcome.put("Procollagen trans-4-hydroxy-L-proline", true);
        candidates2expectedOutcome.put("4-(N-Acetyl-beta-D-glucosaminyl)-beta-D-mannosyl-R", false);
        candidates2expectedOutcome.put("6-(alpha-D-Mannosyl)-beta-D-mannosyl-R", false);
        candidates2expectedOutcome.put("Decanoyl-[acp]", true);
        candidates2expectedOutcome.put("tRNA(Thr)", false);
        candidates2expectedOutcome.put("Protein L-isoaspartate", true);
        candidates2expectedOutcome.put("Triacylglycerol", false);
        candidates2expectedOutcome.put("Tetradecanoyl-[acp]", true);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,3-N-acetyl-alpha-D-galactosaminyl-R", false);
        candidates2expectedOutcome.put("1-Acylglycerol", false);
        candidates2expectedOutcome.put("tRNA(Lys)", false);
        candidates2expectedOutcome.put("(R)-3-Hydroxydodecanoyl-[acp]", true);
        candidates2expectedOutcome.put("3-Oxodecanoyl-[acp]", true);
        candidates2expectedOutcome.put("L-Glutamyl-tRNA(Glu)", false);
        candidates2expectedOutcome.put("O-Phosphoseryl-tRNA(Sec)", false);
        candidates2expectedOutcome.put("Apo-[acetyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("Oligoglycosylglucose", false);
        candidates2expectedOutcome.put("L-Lysyl-tRNA", false);
        candidates2expectedOutcome.put("Peptide L-aspartate", false);
        candidates2expectedOutcome.put("tRNA(Trp)", false);
        candidates2expectedOutcome.put("NDP", false);
        candidates2expectedOutcome.put("5-L-Glutamyl amino acid", false);
        candidates2expectedOutcome.put("trans-Hex-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("2-Acyl-sn-glycero-3-phosphocholine", false);
        candidates2expectedOutcome.put("Sulfatide", false);
        candidates2expectedOutcome.put("Long-chain alcohol", false);
        candidates2expectedOutcome.put("N-Acyl-D-mannosamine 6-phosphate", false);
        candidates2expectedOutcome.put("Glycosyl-N-acylsphingosine", false);
        candidates2expectedOutcome.put("Chondroitin 6-sulfate", false);
        candidates2expectedOutcome.put("tRNA(Gln)", false);
        candidates2expectedOutcome.put("D-Galactosyl-N-acetyl-D-galactosaminyl-(N-acetylneuraminyl)-D- galactosyl-D-glucosylceramide", false);
        candidates2expectedOutcome.put("Ferrocytochrome c", true);
        candidates2expectedOutcome.put("N-Acetyl-D-glucosaminyl-1,3-beta-D-galactosyl-1,4-N-acetyl-beta-D- glucosaminyl-1,3-beta-D-galactosyl-1,4-beta-D-glucosylceramide", false);
        candidates2expectedOutcome.put("ROOH", false);
        candidates2expectedOutcome.put("L-Selenocysteinyl-tRNA(Sec)", false);
        candidates2expectedOutcome.put("Peptide", false);
        candidates2expectedOutcome.put("tRNA(Phe)", false);
        candidates2expectedOutcome.put("4-N-(N-Acetyl-D-glucosaminyl)-protein", true);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactosyl-1,4-N-acetyl-beta-D- glucosaminyl-1,3-beta-D-galactosyl-1,4-D-glucosylceramide", false);
        candidates2expectedOutcome.put("Acetoacetyl-[acp]", true);
        candidates2expectedOutcome.put("L-Threonyl-tRNA(Thr)", false);
        candidates2expectedOutcome.put("R'C(R)SH", false);
        candidates2expectedOutcome.put("Peptide 2-(3-carboxy-3-aminopropyl)-L-histidine", false);
        candidates2expectedOutcome.put("1-Phosphatidyl-1D-myo-inositol 3,5-bisphosphate", false);
        candidates2expectedOutcome.put("Protein-L-arginine", true);
        candidates2expectedOutcome.put("Alkylamine", false);
        candidates2expectedOutcome.put("Peptide 3-hydroxy-L-aspartate", false);
        candidates2expectedOutcome.put("Methionyl peptide", false);
        candidates2expectedOutcome.put("Protein dithiol", true);
        candidates2expectedOutcome.put("3-Oxododecanoyl-[acp]", true);
        candidates2expectedOutcome.put("N-Substituted amino acid", false);
        candidates2expectedOutcome.put("Heparosan-N-sulfate D-glucuronate", false);
        candidates2expectedOutcome.put("alpha-D-Galactosyl-(1,3)-[alpha-L-fucosyl-(1,2)]-D-galactoside", false);
        candidates2expectedOutcome.put("L-Aspartyl-tRNA(Asp)", false);
        candidates2expectedOutcome.put("Retinyl ester", false);
        candidates2expectedOutcome.put("Dolichyl diphosphooligosaccharide", false);
        candidates2expectedOutcome.put("Diacylglycerol", false);
        candidates2expectedOutcome.put("L-Methionyl-tRNA", false);
        candidates2expectedOutcome.put("Glucosylceramide", false);
        candidates2expectedOutcome.put("[Enzyme]-cysteine", true);
        candidates2expectedOutcome.put("[eIF5A-precursor]-lysine", true);
        candidates2expectedOutcome.put("Protein tyrosine-O-sulfate", true);
        candidates2expectedOutcome.put("5-(D-Galactosyloxy)-L-lysine-procollagen", true);
        candidates2expectedOutcome.put("Aryl dialkyl phosphate", false);
        candidates2expectedOutcome.put("3-Oxo acid", false);
        candidates2expectedOutcome.put("Thioredoxin", true);
        candidates2expectedOutcome.put("S-Aryl-L-cysteine", false);
        candidates2expectedOutcome.put("N-Acyl-L-aspartate", false);
        candidates2expectedOutcome.put("Galactosylceramide", false);
        candidates2expectedOutcome.put("Epoxide", false);
        candidates2expectedOutcome.put("Globoside", false);
        candidates2expectedOutcome.put("1-Phosphatidyl-D-myo-inositol 4,5-bisphosphate", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,6-beta-D-galactosyl-1,4-N-acetyl-D- glucosaminyl-R", false);
        candidates2expectedOutcome.put("Deoxynucleoside triphosphate", false);
        candidates2expectedOutcome.put("1-Alkyl-sn-glycero-3-phosphoethanolamine", false);
        candidates2expectedOutcome.put("Dihydrolipoylprotein", true);
        candidates2expectedOutcome.put("tRNA(Leu)", false);
        candidates2expectedOutcome.put("Retinyl-ester-(cellular-retinol-binding-protein)", true);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,8-alpha-N-acetylneuraminyl-2,3-beta-D- galactosyl-R", false);
        candidates2expectedOutcome.put("2-Oxo acid", false);
        candidates2expectedOutcome.put("1-Acyl-sn-glycerol 3-phosphate", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-galactosaminyl-R", false);
        candidates2expectedOutcome.put("Detyrosinated alpha-tubulin", true);
        candidates2expectedOutcome.put("RNA 3'-terminal-phosphate", false);
        candidates2expectedOutcome.put("1,4-beta-D-Mannan", false);
        candidates2expectedOutcome.put("Aldose", false);
        candidates2expectedOutcome.put("2',3'-Cyclic nucleotide", false);
        candidates2expectedOutcome.put("1-Phosphatidyl-D-myo-inositol", false);
        candidates2expectedOutcome.put("[Pyruvate dehydrogenase (acetyl-transferring)]", true);
        candidates2expectedOutcome.put("Methylated amine", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,3-N-acetyl-D-galactosaminyl-R", false);
        candidates2expectedOutcome.put("Protein tyrosine phosphate", true);
        candidates2expectedOutcome.put("Maltodextrin", false);
        candidates2expectedOutcome.put("alpha-Tubulin", true);
        candidates2expectedOutcome.put("5'-Ribonucleotide", false);
        candidates2expectedOutcome.put("Histone N(omega)-methyl-L-arginine", true);
        candidates2expectedOutcome.put("DNA", false);
        candidates2expectedOutcome.put("3'-Phosphopolynucleotide", false);
        candidates2expectedOutcome.put("[Isocitrate dehydrogenase (NADP+)] phosphate", true);
        candidates2expectedOutcome.put("Lipoylprotein", true);
        candidates2expectedOutcome.put("Cholesterol ester", false);
        candidates2expectedOutcome.put("Apo-[methylmalonyl-CoA:pyruvate carboxytransferase]", true);
        candidates2expectedOutcome.put("Phospho-beta-adrenergic receptor", true);
        candidates2expectedOutcome.put("N-Acetyl-D-glucosaminylphosphatidylinositol", false);
        candidates2expectedOutcome.put("N-Acylglycine", false);
        candidates2expectedOutcome.put("(3R)-3-Hydroxydecanoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("Peptidyl-allysyl-peptide", false);
        candidates2expectedOutcome.put("DNA containing guanine", false);
        candidates2expectedOutcome.put("5'-Phosphopolynucleotide", false);
        candidates2expectedOutcome.put("Octanoyl-[acp]", true);
        candidates2expectedOutcome.put("Protein C-terminal S-farnesyl-L-cysteine methyl ester", true);
        candidates2expectedOutcome.put("[Acetyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("Chondroitin", false);
        candidates2expectedOutcome.put("Long-chain acid anion", false);
        candidates2expectedOutcome.put("3-Oxoacyl-CoA", false);
        candidates2expectedOutcome.put("2-Hydroxy carboxylate", false);
        candidates2expectedOutcome.put("L-Tyrosyl-tRNA(Tyr)", false);
        candidates2expectedOutcome.put("5'-Dephospho-DNA", false);
        candidates2expectedOutcome.put("trans,trans-2,3,4,5-Tetradehydroacyl-CoA", false);
        candidates2expectedOutcome.put("Protein N6-methyl-L-lysine", true);
        candidates2expectedOutcome.put("DNA 6-methylaminopurine", false);
        candidates2expectedOutcome.put("Carboxylate", false);
        candidates2expectedOutcome.put("(3R)-3-Hydroxypalmitoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("(5')ppPur-mRNA", false);
        candidates2expectedOutcome.put("Protein N6-(dihydrolipoyl)lysine", true);
        candidates2expectedOutcome.put("Myosin light chain phosphate", true);
        candidates2expectedOutcome.put("Lipid hydroperoxide", false);
        candidates2expectedOutcome.put("Carboxybiotin-carboxyl-carrier protein", true);
        candidates2expectedOutcome.put("Alkane", false);
        candidates2expectedOutcome.put("Ferricytochrome c", true);
        candidates2expectedOutcome.put("Nucleoside triphosphate", false);
        candidates2expectedOutcome.put("Enzyme N6-(dihydrolipoyl)lysine", true);
        candidates2expectedOutcome.put("N-Acetyl-alpha-D-glucosaminyl-(1->4)-beta-D-glucuronosylproteoglycan", false);
        candidates2expectedOutcome.put("trans-Tetradec-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("Long-chain carboxylate", false);
        candidates2expectedOutcome.put("S-Aminomethyldihydrolipoylprotein", true);
        candidates2expectedOutcome.put("Alditol", false);
        candidates2expectedOutcome.put("Peptidylproline (omega=180)", false);
        candidates2expectedOutcome.put("Protein L-cysteine", true);
        candidates2expectedOutcome.put("alpha-N-Acetylneuraminyl-2,3-beta-D-galactosyl-1,3-N-acetyl-alpha-D- galactosaminyl-R", false);
        candidates2expectedOutcome.put("Protein L-citrulline", true);
        candidates2expectedOutcome.put("N-Tetradecanoylglycylpeptide", false);
        candidates2expectedOutcome.put("D-Xylosylprotein", true);
        candidates2expectedOutcome.put("Protein N6,N6,N6-trimethyl-L-lysine", true);
        candidates2expectedOutcome.put("Peptide 2-[3-carboxy-3-(methylammonio)propyl]-L-histidine", false);
        candidates2expectedOutcome.put("6-(2-[N-Acetyl-beta-D-glucosaminyl]-alpha-D-mannosyl)-beta-D- mannosyl-R", false);
        candidates2expectedOutcome.put("Hyaluronate", false);
        candidates2expectedOutcome.put("Protein N6-(lipoyl)lysine", true);
        candidates2expectedOutcome.put("N-Acetyl-D-galactosaminyl-N-Acetyl-D-galactosaminyl-1,3-D- galactosyl-1,4-D-galactosyl-1,4-D-glucosylceramide", false);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,4-N-acetyl-D-glucosaminyl-glycoprotein", true);
        candidates2expectedOutcome.put("Protein asparagine", true);
        candidates2expectedOutcome.put("Protein lysine", true);
        candidates2expectedOutcome.put("S-(2-Hydroxyacyl)glutathione", false);
        candidates2expectedOutcome.put("tRNA(Cys)", false);
        candidates2expectedOutcome.put("(3R)-3-Hydroxytetradecanoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("(5-L-Glutamyl)-peptide", false);
        candidates2expectedOutcome.put("Nucleoside 2'-phosphate", false);
        candidates2expectedOutcome.put("Peptide beta-D-galactosyl-(1->3)-N-acetyl-alpha-D-galactosaminyl-L-serine", false);
        candidates2expectedOutcome.put("[Pyruvate dehydrogenase (acetyl-transferring)] phosphate", true);
        candidates2expectedOutcome.put("RX", false);
        candidates2expectedOutcome.put("Heparosan-N-sulfate L-iduronate", false);
        candidates2expectedOutcome.put("trans-Hexadec-2-enoyl-[acp]", true);
        candidates2expectedOutcome.put("L-Isoleucyl-tRNA(Ile)", false);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,4-N-acetyl-beta-D-glucosaminylglycopeptide", false);
        candidates2expectedOutcome.put("Chondroitin 4-sulfate", false);
        candidates2expectedOutcome.put("2-Arylethylamine", false);
        candidates2expectedOutcome.put("L-Seryl-tRNA(Ser)", false);
        candidates2expectedOutcome.put("N-Acylneuraminate", false);
        candidates2expectedOutcome.put("N-Acetyl-D-glucosaminyl-1,3-beta-D-galactosyl-1,4-D- glucosylceramide", false);
        candidates2expectedOutcome.put("2-(2-Hydroxyacyl)sphingosine", false);
        candidates2expectedOutcome.put("tRNA guanine", false);
        candidates2expectedOutcome.put("Hexadecenoyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("N-Acetyl-D-galactosaminyl-(N-acetylneuraminyl)-D-galactosyl-D- glucosylceramide", false);
        candidates2expectedOutcome.put("L-Arginyl-tRNA(Arg)", false);
        candidates2expectedOutcome.put("1-(beta-D-Galactosyl)-2-(2-hydroxyacyl)sphingosine", false);
        candidates2expectedOutcome.put("N-Acylneuraminate 9-phosphate", false);
        candidates2expectedOutcome.put("(3S)-3-Hydroxyacyl-CoA", false);
        candidates2expectedOutcome.put("1,2-D-Glucosyl-5-D-(galactosyloxy)-L-lysine-procollagen", true);
        candidates2expectedOutcome.put("[Methionine synthase]-methylcob(I)alamin", true);
        candidates2expectedOutcome.put("Polynucleotide", false);
        candidates2expectedOutcome.put("L-Histidyl-tRNA(His)", false);
        candidates2expectedOutcome.put("tRNA(Glu)", false);
        candidates2expectedOutcome.put("Oxidized thiol-containing reductant", false);
        candidates2expectedOutcome.put("L-Arginyl-protein", true);
        candidates2expectedOutcome.put("Hexanoyl-[acp]", true);
        candidates2expectedOutcome.put("1-Phosphatidyl-1D-myo-inositol 3-phosphate", false);
        candidates2expectedOutcome.put("Primary amine", false);
        candidates2expectedOutcome.put("DNA containing 6-O-methylguanine", false);
        candidates2expectedOutcome.put("Primary alcohol", false);
        candidates2expectedOutcome.put("L-Glutaminyl-peptide", false);
        candidates2expectedOutcome.put("1-Phosphatidyl-1D-myo-inositol 5-phosphate", false);
        candidates2expectedOutcome.put("Carboxylic ester", false);
        candidates2expectedOutcome.put("tRNA(Val)", false);
        candidates2expectedOutcome.put("1,3-beta-D-Galactosyl-N-acetyl-D-glucosaminyl-R", false);
        candidates2expectedOutcome.put("L-Tryptophanyl-tRNA(Trp)", false);
        candidates2expectedOutcome.put("3-Hydroxyacyl group of bacterial toxin", false);
        candidates2expectedOutcome.put("Rhodopsin", true);
        candidates2expectedOutcome.put("Acyl-carrier protein", true);
        candidates2expectedOutcome.put("tRNA containing N1-methyladenine", false);
        candidates2expectedOutcome.put("Histone-L-lysine", true);
        candidates2expectedOutcome.put("L-Valyl-tRNA(Val)", false);
        candidates2expectedOutcome.put("Aldehyde", false);
        candidates2expectedOutcome.put("[3-Methylcrotonoyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("beta-D-Galactosyl-R", false);
        candidates2expectedOutcome.put("N-Acyl-L-amino acid", false);
        candidates2expectedOutcome.put("Ceramide 1-phosphate", false);
        candidates2expectedOutcome.put("1-Acyl-sn-glycero-3-phosphocholine", false);
        candidates2expectedOutcome.put("Steryl ester", false);
        candidates2expectedOutcome.put("Heparan sulfate N-acetyl-alpha-D-glucosaminide", false);
        candidates2expectedOutcome.put("GM3", false);
        candidates2expectedOutcome.put("Malonyl-[acyl-carrier protein]", true);
        candidates2expectedOutcome.put("beta-D-Glucuronoside", false);
        candidates2expectedOutcome.put("tRNA containing 6-isopentenyladenosine", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,2-alpha-D-mannosyl-1,3-(R1)-beta-D- mannosyl-R2", false);
        candidates2expectedOutcome.put("L-Cysteinyl-tRNA(Cys)", false);
        candidates2expectedOutcome.put("tRNA pseudouridine", false);
        candidates2expectedOutcome.put("tRNA(Ala)", false);
        candidates2expectedOutcome.put("Apo-[3-methylcrotonoyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("tRNA", false);
        candidates2expectedOutcome.put("O-D-Mannosylprotein", true);
        candidates2expectedOutcome.put("Nalpha-Acetylpeptide", false);
        candidates2expectedOutcome.put("Acylglycerone phosphate", false);
        candidates2expectedOutcome.put("Nucleoside 5'-phosphate", false);
        candidates2expectedOutcome.put("3-Oxohexanoyl-[acp]", true);
        candidates2expectedOutcome.put("tRNA(Gly)", false);
        candidates2expectedOutcome.put("Ribonucleoside", false);
        candidates2expectedOutcome.put("1-Phosphatidyl-1D-myo-inositol 4-phosphate", false);
        candidates2expectedOutcome.put("tRNA uridine", false);
        candidates2expectedOutcome.put("Formyl-L-methionyl peptide", false);
        candidates2expectedOutcome.put("RNA terminal-2',3'-cyclic-phosphate", false);
        candidates2expectedOutcome.put("Protein-omega-N-(ADP-D-ribosyl)-L-arginine", true);
        candidates2expectedOutcome.put("Heparan sulfate alpha-D-glucosaminide", false);
        candidates2expectedOutcome.put("beta-D-Galactosyl-1,4-N-acetyl-D-glucosaminyl-R", false);
        candidates2expectedOutcome.put("(2S)-2-Methylacyl-CoA", false);
        candidates2expectedOutcome.put("(R)-3-Hydroxyhexanoyl-[acp]", true);
        candidates2expectedOutcome.put("Myosin light chain", true);
        candidates2expectedOutcome.put("3-beta-D-Galactosyl-4-beta-D-galactosyl-O-beta-D-xylosylprotein", true);
        candidates2expectedOutcome.put("[Methionine synthase]-cob(II)alamin", true);
        candidates2expectedOutcome.put("[Dihydrolipoyllysine-residue (2-methylpropanoyl)transferase] S-(2-methylpropanoyl)dihydrolipoyllysine", true);
        candidates2expectedOutcome.put("tRNA containing N7-methylguanine", false);
        candidates2expectedOutcome.put("Holo-[carboxylase]", true);
        candidates2expectedOutcome.put("Amylose", false);
        candidates2expectedOutcome.put("Aryl thiol", false);
        candidates2expectedOutcome.put("R'C(R)S-S(R)CR'", false);
        candidates2expectedOutcome.put("(S)-2-Hydroxy acid", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,6-(N-acetyl-beta-D-glucosaminyl-1,2)- alpha-D-mannosyl-R", false);
        candidates2expectedOutcome.put("R-S-Glutathione", false);
        candidates2expectedOutcome.put("Histone N6-methyl-L-lysine", true);
        candidates2expectedOutcome.put("beta-D-Glucuronosyl-(1->4)-N-acetyl-alpha-D-glucosaminyl-(1->4)- beta-D-glucuronosylproteoglycan", false);
        candidates2expectedOutcome.put("L-Prolyl-tRNA(Pro)", false);
        candidates2expectedOutcome.put("N-Acetyl-beta-D-glucosaminyl-1,4-(N-acetyl-beta-D-glucosaminyl-1,2)- alpha-D-mannosyl-1,3-beta-D-mannosyl-R", false);
        candidates2expectedOutcome.put("2-Acetyl-1-alkyl-sn-glycero-3-phosphocholine", false);
        candidates2expectedOutcome.put("Apo-[propionyl-CoA:carbon-dioxide ligase (ADP-forming)]", true);
        candidates2expectedOutcome.put("Nitrile", false);
        candidates2expectedOutcome.put("Dermatan 6'-sulfate", false);
        candidates2expectedOutcome.put("XYZa protein-<i>S</i>-methyl-L-cysteine", true);
    }

    @After
    public void tearDown() {
    }

    /**
     * Test of isProteinName method, of class ProteinSmallMoleculeDecider.
     */
    @Test
    public void testIsProteinName() {
        System.out.println("isProteinName");
        System.out.println("Size: "+candidates2expectedOutcome.size());
        for (String name : this.candidates2expectedOutcome.keySet()) {
            boolean expResult = candidates2expectedOutcome.get(name);
            boolean result = ProteinSmallMoleculeDecider.isProteinName(name);
            System.out.println("candidates2expectedOutcome.put(\"" + name + "\"," + result + ");");
            assertEquals(expResult,result);
        }

        /*assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");*/
    }
}
