//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.21 at 12:42:32 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bbk.ac.uk/rex/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.bbk.ac.uk/rex/", prefix = "rex")
})
package uk.ac.ebi.mdk.io.xml.rex;
